### ISSUE TITLE
get请求端口号写死了

### ISSUE THREAD

**Issue by swagger-coder** [LSTM-Kirigaya/go-cqhttp-python-server#1]
get_request = "http://127.0.0.1:5700/send_private_msg?user_id={}&message={}".format(user_id, message)
get请求端口号写死了，一台服务器多个机器人就出错了

**Comment by LSTM-Kirigaya** [comment]
是的，我假设只有一个机器人，不支持多机器人，抱歉，readme里面没有写清楚。如果需要，你只需要手动修改GET与POST的端口号即可。

**Comment by LSTM-Kirigaya** [comment]
同一个IP发出多个QQ登录请求有较大风险，不推荐同一台服务器登录多个QQ。如果要登录，请极可能使得它们的设备号不一样。

**Comment by swagger-coder** [comment]
好嘞谢谢



---原始邮件---
发件人: "Kirigaya ***@***.***&gt;
发送时间: 2023年2月16日(周四) 下午5:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LSTM-Kirigaya/go-cqhttp-python-server] get请求端口号写死了 (Issue #1)




 
同一个IP发出多个QQ登录请求有较大风险，不推荐同一台服务器登录多个QQ。如果要登录，请极可能使得它们的设备号不一样。
